### ISSUE TITLE
Hey, when trying to run the UMD Bundle example, this happens

### ISSUE THREAD

**Issue by LinusHats** [fskpf/svg2roughjs#91]
Hey, when trying to run the UMD Bundle example, this happens: 

```
Uncaught TypeError: Cannot read properties of undefined (reading 'unitType')
    at t.Svg2Roughjs.coerceSize (Svg2Roughjs.js:278:39)
    at set svg [as svg] (Svg2Roughjs.js:79:42)
    [...]
```

**To Reproduce**
One of the SVGs i was trying it on:
```
<svg width="60mm" height="60mm" viewBox="0 0 60 60" xmlns="http://www.w3.org/2000/svg">
	<g id="AngleBallValve">
		<circle cx="30.01" cy="30.01" r="10.00" stroke="#01A6D6" stroke-width="1.00" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray="0" pathLength="100.00" />
		<polyline points="35.30,38.50 42.49,50.01 20.00,50.01 25.54,38.95 "  stroke="#01A6D6" stroke-width="1.00" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray="0" pathLength="100.00"  />
		<polyline points="21.07,34.48 10.00,40.01 10.00,20.00 21.07,25.54 "  stroke="#01A6D6" stroke-width="1.00" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray="0" pathLength="100.00"  />
	</g>
</svg>
```

I thought it would give me some kind of sketched version of the SVG

**Comment by fskpf** [comment]
How did you try it exactly? 

Here is a running example with the UMD bundle and your mentioned SVG: https://jsfiddle.net/bc4ywxs2/
